# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PbjWnWNsUo7TUZbZ9QFZF00SQ5Zah84K
"""

from flask import Flask, request, jsonify, send_from_directory
import os
import subprocess
import uuid

app = Flask(__name__)

INPUT_FOLDER = "input_video"
OUTPUT_FOLDER = "output_video"

os.makedirs(INPUT_FOLDER, exist_ok=True)
os.makedirs(OUTPUT_FOLDER, exist_ok=True)


@app.route("/")
def home():
    return send_from_directory("static", "index.html")


@app.route("/static/<path:filename>")
def static_files(filename):
    return send_from_directory("static", filename)


@app.route("/analyse", methods=["POST"])
def analyse():
    if "video" not in request.files:
        return jsonify({"error": "No video uploaded"}), 400

    video = request.files["video"]

    if video.filename == "":
        return jsonify({"error": "No selected file"}), 400

    file_id = str(uuid.uuid4())

    input_path = os.path.join(INPUT_FOLDER, f"{file_id}.mp4")
    output_path = os.path.join(OUTPUT_FOLDER, f"{file_id}_output.mp4")

    video.save(input_path)

    try:
        subprocess.run(
            ["python", "output_classification33.py", input_path, output_path],
            check=True
        )

        return jsonify({
            "message": "Analysis completed",
            "output_video": f"/output_video/{file_id}_output.mp4"
        })

    except subprocess.CalledProcessError as e:
        return jsonify({"error": "Video analysis failed"}), 500


@app.route("/output_video/<path:filename>")
def output_video(filename):
    return send_from_directory(OUTPUT_FOLDER, filename)


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000,debug=False)
